### ISSUE TITLE
Does it support python 3.6?

### ISSUE THREAD

**Issue by xuexingdong** [openatx/facebook-wda#38]
I got module 'wda' has no attribute 'Client' error when using python3.6

**Comment by codeskyblue** [comment]
it works on 3.6

**Comment by xuexingdong** [comment]
感谢答主回复，已经解决了，是因为我的包名也叫wda 哈哈哈
感觉这个库要因为微信跳一跳外挂火了（ps：我也是做这个才下的）

**Comment by codeskyblue** [comment]
刚发现怎么star怎么突然这么多

**Comment by codeskyblue** [comment]
@xuexingdong iOS我还没试过，跳一跳的效果怎么样？

**Comment by xuexingdong** [comment]
自己写的 随便玩玩而已 没过多优化 用轮廓+面积的方法识别了棋子 还蛮准的
背景色这一块做的比较差 用rgb过滤但后面颜色会变效果就不好了 渐变的策略还没做
热度过去兴趣转移了 不打算继续了  就元旦放假倒腾倒腾
最先做出来的是这位同学 四天6000star。。。
[https://github.com/wangshub/wechat_jump_game](https://github.com/wangshub/wechat_jump_game)
